### PR TITLE
Base django 1.11 support

### PR DESCRIPTION
**Pull request by ahsan-ul-haq**

### CODE REVIEW

**Comment by clintonb** [comment]
Why do we need any changes beyond the first commit? We don't really want/need to maintain this longterm. The goal was simply to get this working for Django 1.11.

**Comment by clintonb** [comment]
Now that #2 has been merged, this PR isn't really necessary.

**Comment by ahsan-ul-haq** [comment]
Those commits were merged in base-django-1.11-support branch now this will be merged in master

**Comment by clintonb** [comment]
My question is: why do we need your two extra commits? They are nice-to-have, but not really necessary for Django 1.11 support.

**Comment by ahsan-ul-haq** [comment]
@clintonb removed the extra commit

**Pull request merged**
